import {
  AlertTriangle,
  AlignLeft,
  ArrowRight,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  Cookie,
  CreditCard,
  File,
  FileText,
  FolderKey,
  HardDrive,
  HelpCircle,
  Image,
  KeyboardIcon,
  Laptop,
  Loader2,
  LucideProps,
  MegaphoneOff,
  MonitorCheck,
  Moon,
  MoreVertical,
  MountainSnow,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
} from "lucide-react"

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  cookie: Cookie,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  hamburger: AlignLeft,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  folder: FolderKey,
  hardDrive: HardDrive,
  monitorCheck: MonitorCheck,
  mountain: MountainSnow,
  keyboard: KeyboardIcon,
  twitter: Twitter,
  check: Check,
  megaphone: MegaphoneOff,
  calendar: CalendarDays,
}
